Create Table CUSTOMER
(CUSTOMERID Integer Primary Key,
CUSTOMERNAME VarChar(1000),
CUSTOMERPHONE VarChar(1000),
CUSTOMERADDRESS VarChar(1000));

Create Table PRODUCT
(PRODUCTID Integer Primary Key,
PRODNAME VarChar(1000),
PRODPRICE VarChar(1000),
PRODDESC VarChar(1000));

Create Table SERVICE
(SERVICEID Integer Primary Key,
SERVNAME VarChar(1000),
SERVLEVEL VarChar(1000),
SERVTOWN VarChar(1000));

Create Table STORE
(STOREID Integer Primary Key,
STORENAME VarChar(1000));

Create Table STOREAREA
(STOREAREAID Integer Primary Key,
SERVCENTERNAME VarChar(1000),
SERVICEDEPT VarChar(1000),
DEPTDESC VarChar(1000));

Create Table SUPPLIER
(SUPPLIERID Integer Primary Key,
SUPPLIERADDRESS VarChar(1000),
CONTACTNAME VarChar(1000),
CONTACTPHONE VarChar(1000),
CONTACTEMAIL VarChar(1000));

Create Table TECHNICIAN
(TECHNUM Integer Primary Key,
TECHNAME VarChar(1000));

Create Table CUSTPRODORDER
(CUSTOMERID integer,
PRODUCTID integer,
PrimaryKey (CUSTOMERID, PRODUCTID),
Foreign Key (CUSTOMERID) REFERENCES CUSTOMER,
Foreign Key (PRODUCTID) REFERENCES PRODUCT);

Create Table CUSTSERVORDER
(CUSTOMERID integer,
SERVICEID integer,
PrimaryKey (CUSTOMERID, SERVICEID),
Foreign Key (CUSTOMERID) REFERENCES CUSTOMER,
Foreign Key (SERVICEID) REFERENCES SERVICE);

Create Table TECHSERVORDER
(TECHNUM integer,
SERVICEID integer,
PrimaryKey (TECHNUM, SERVICEID),
Foreign Key (TECHNUM) REFERENCES TECHNICIAN,
Foreign Key (SERVICEID) REFERENCES SERVICE);




